name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        build_mode: [release, release-static]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Rust cache
        uses: Swatinem/rust-cache@c676846f29d98ff6b0106d3608c7ffd4048af17b # v2.9.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            sudo apt-get install -y musl-tools
          else
            sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu
          fi
        
      - name: Install Rust toolchains
        run: make setup

      - name: Build ${{ matrix.build_mode }}
        run: |
          if [ "${{ matrix.build_mode }}" = "release" ]; then
            if [ "${{ matrix.arch }}" = "amd64" ]; then
              make release
            else
              make release-arm64
            fi
          else
            if [ "${{ matrix.arch }}" = "amd64" ]; then
              make release-static
            else
              make release-static-arm64
            fi
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: couic-${{ matrix.arch }}-${{ matrix.build_mode }}
          path: release/*